// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         subId: "subId"
 *     }
 */
export interface DeleteWebhooksIdDeliveriesSubIdRequest {
    /** Webhook ID */
    id: string;
    /** Deliverie ID */
    subId: string;
}
