// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Forum from "../../../index.js";

export declare namespace ThreadsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ThreadsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ThreadsClient.Options>;

    constructor(options: ThreadsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {Forum.GetThreadsRequest} request
     * @param {ThreadsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.threads.listAllThreads()
     */
    public listAllThreads(
        request: Forum.GetThreadsRequest = {},
        requestOptions?: ThreadsClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.GetThreadsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listAllThreads(request, requestOptions));
    }

    private async __listAllThreads(
        request: Forum.GetThreadsRequest = {},
        requestOptions?: ThreadsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.GetThreadsResponse>> {
        const { page, limit, search } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        if (search != null) {
            _queryParams.search = search;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                "threads",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.GetThreadsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/threads");
    }

    /**
     * @param {Forum.PostThreadsRequest} request
     * @param {ThreadsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.BadRequestError}
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.threads.createAThread({
     *         title: "title",
     *         body: "body"
     *     })
     */
    public createAThread(
        request: Forum.PostThreadsRequest,
        requestOptions?: ThreadsClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.PostThreadsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createAThread(request, requestOptions));
    }

    private async __createAThread(
        request: Forum.PostThreadsRequest,
        requestOptions?: ThreadsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.PostThreadsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                "threads",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.PostThreadsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Forum.BadRequestError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/threads");
    }

    /**
     * @param {Forum.GetThreadsIdRequest} request
     * @param {ThreadsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.threads.getAThread({
     *         id: "id"
     *     })
     */
    public getAThread(
        request: Forum.GetThreadsIdRequest,
        requestOptions?: ThreadsClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.GetThreadsIdResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getAThread(request, requestOptions));
    }

    private async __getAThread(
        request: Forum.GetThreadsIdRequest,
        requestOptions?: ThreadsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.GetThreadsIdResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `threads/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.GetThreadsIdResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/threads/{id}");
    }

    /**
     * @param {Forum.DeleteThreadsIdRequest} request
     * @param {ThreadsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.threads.deleteAThread({
     *         id: "id"
     *     })
     */
    public deleteAThread(
        request: Forum.DeleteThreadsIdRequest,
        requestOptions?: ThreadsClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.DeleteThreadsIdResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteAThread(request, requestOptions));
    }

    private async __deleteAThread(
        request: Forum.DeleteThreadsIdRequest,
        requestOptions?: ThreadsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.DeleteThreadsIdResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `threads/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.DeleteThreadsIdResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/threads/{id}");
    }

    /**
     * @param {Forum.PatchThreadsIdRequest} request
     * @param {ThreadsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.BadRequestError}
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.threads.updateAThread({
     *         id: "id"
     *     })
     */
    public updateAThread(
        request: Forum.PatchThreadsIdRequest,
        requestOptions?: ThreadsClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.PatchThreadsIdResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateAThread(request, requestOptions));
    }

    private async __updateAThread(
        request: Forum.PatchThreadsIdRequest,
        requestOptions?: ThreadsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.PatchThreadsIdResponse>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `threads/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.PatchThreadsIdResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Forum.BadRequestError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/threads/{id}");
    }
}
