// This file was auto-generated by Fern from our API Definition.

export interface GetReportsResponse {
    data: GetReportsResponse.Data.Item[];
    meta: GetReportsResponse.Meta;
}

export namespace GetReportsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Report type (e.g. spam, abuse) */
            type: string;
            /** Reason for reporting */
            description?: string;
            /** Reporter user ID (required for API key auth, ignored for JWT auth) */
            userId?: string;
            /** ID of user being reported */
            reportedId?: string;
            /** ID of thread being reported */
            threadId?: string;
            /** ID of post being reported */
            postId?: string;
            /** ID of private message being reported */
            privateMessageId?: string;
            id: string;
            /** Report status (pending, reviewed, resolved, dismissed) */
            status: string | null;
            /** Report creation timestamp */
            createdAt: string;
            /** Report last update timestamp */
            updatedAt: string;
        }
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
