// This file was auto-generated by Fern from our API Definition.

export interface GetSsoIdResponse {
    data: GetSsoIdResponse.Data;
}

export namespace GetSsoIdResponse {
    export type Data = {};
}
