// This file was auto-generated by Fern from our API Definition.

export interface GetSsoResponse {
    data: GetSsoResponse.Data.Item[];
    meta: GetSsoResponse.Meta;
}

export namespace GetSsoResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export type Item = {};
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
