// This file was auto-generated by Fern from our API Definition.

export interface PostSsoResponse {
    data: PostSsoResponse.Data;
}

export namespace PostSsoResponse {
    export type Data = {};
}
