// This file was auto-generated by Fern from our API Definition.

export interface GetTagsIdSubscribersSubIdResponse {
    data: GetTagsIdSubscribersSubIdResponse.Data;
}

export namespace GetTagsIdSubscribersSubIdResponse {
    export type Data = {};
}
