// This file was auto-generated by Fern from our API Definition.

export interface GetTagsResponse {
    data: GetTagsResponse.Data.Item[];
    meta: GetTagsResponse.Meta;
}

export namespace GetTagsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Tag name */
            name: string;
            /** Tag slug (unique identifier) */
            slug?: string;
            /** Tag description */
            description?: string;
            /** Hex color code */
            color?: string;
            /** Extended data */
            extendedData?: Record<string, unknown>;
            id: string;
        }
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
