// This file was auto-generated by Fern from our API Definition.

export interface GetPrivateMessagesResponse {
    data: GetPrivateMessagesResponse.Data.Item[];
    meta: GetPrivateMessagesResponse.Meta;
}

export namespace GetPrivateMessagesResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export type Item = {};
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
