// This file was auto-generated by Fern from our API Definition.

export interface GetPrivateMessagesIdResponse {
    data: GetPrivateMessagesIdResponse.Data;
}

export namespace GetPrivateMessagesIdResponse {
    export type Data = {};
}
