// This file was auto-generated by Fern from our API Definition.

export interface GetPrivateMessagesIdRepliesSubIdResponse {
    data: GetPrivateMessagesIdRepliesSubIdResponse.Data;
}

export namespace GetPrivateMessagesIdRepliesSubIdResponse {
    export type Data = {};
}
