// This file was auto-generated by Fern from our API Definition.

export interface PostPrivateMessagesIdRepliesResponse {
    data: PostPrivateMessagesIdRepliesResponse.Data;
}

export namespace PostPrivateMessagesIdRepliesResponse {
    export type Data = {};
}
