// This file was auto-generated by Fern from our API Definition.

export interface PostPrivateMessagesResponse {
    data: PostPrivateMessagesResponse.Data;
}

export namespace PostPrivateMessagesResponse {
    export type Data = {};
}
