// This file was auto-generated by Fern from our API Definition.

export interface GetWebhooksIdDeliveriesSubIdResponse {
    data: GetWebhooksIdDeliveriesSubIdResponse.Data;
}

export namespace GetWebhooksIdDeliveriesSubIdResponse {
    export type Data = {};
}
