// This file was auto-generated by Fern from our API Definition.

export interface GetWebhooksResponse {
    data: GetWebhooksResponse.Data.Item[];
    meta: GetWebhooksResponse.Meta;
}

export namespace GetWebhooksResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export type Item = {};
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
