// This file was auto-generated by Fern from our API Definition.

export interface GetWebhooksIdResponse {
    data: GetWebhooksIdResponse.Data;
}

export namespace GetWebhooksIdResponse {
    export type Data = {};
}
