// This file was auto-generated by Fern from our API Definition.

export interface PostWebhooksResponse {
    data: PostWebhooksResponse.Data;
}

export namespace PostWebhooksResponse {
    export type Data = {};
}
