// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         subId: "subId"
 *     }
 */
export interface DeletePrivateMessagesIdRepliesSubIdRequest {
    /** Private Message ID */
    id: string;
    /** Replie ID */
    subId: string;
}
