// This file was auto-generated by Fern from our API Definition.

export interface GetUsersIdResponse {
    data?: GetUsersIdResponse.Data;
}

export namespace GetUsersIdResponse {
    export interface Data {
        /** Items per page (max 75) */
        limit?: number;
        /** Cursor for pagination */
        cursor?: string;
        /** Search by username or display name */
        search?: string;
        /** Sort by creation date */
        sort?: Data.Sort;
    }

    export namespace Data {
        /** Sort by creation date */
        export const Sort = {
            Newest: "newest",
            Oldest: "oldest",
        } as const;
        export type Sort = (typeof Sort)[keyof typeof Sort];
    }
}
