// This file was auto-generated by Fern from our API Definition.

export interface GetUsersResponse {
    data: GetUsersResponse.Data.Item[];
    meta: GetUsersResponse.Meta;
}

export namespace GetUsersResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Items per page (max 75) */
            limit?: number;
            /** Cursor for pagination */
            cursor?: string;
            /** Search by username or display name */
            search?: string;
            /** Sort by creation date */
            sort?: Item.Sort;
        }

        export namespace Item {
            /** Sort by creation date */
            export const Sort = {
                Newest: "newest",
                Oldest: "oldest",
            } as const;
            export type Sort = (typeof Sort)[keyof typeof Sort];
        }
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
