// This file was auto-generated by Fern from our API Definition.

export interface GetUsersIdFollowingSubIdResponse {
    data: GetUsersIdFollowingSubIdResponse.Data;
}

export namespace GetUsersIdFollowingSubIdResponse {
    export type Data = {};
}
