// This file was auto-generated by Fern from our API Definition.

export interface NotificationList {
    /** Items per page (max 75) */
    limit?: number;
    /** Cursor for pagination */
    cursor?: string;
    /** Filter unread notifications */
    unreadOnly?: NotificationList.UnreadOnly;
    /** Filter by user ID (admin only) */
    userId?: string;
}

export namespace NotificationList {
    /** Filter unread notifications */
    export const UnreadOnly = {
        True: "true",
        False: "false",
    } as const;
    export type UnreadOnly = (typeof UnreadOnly)[keyof typeof UnreadOnly];
}
