// This file was auto-generated by Fern from our API Definition.

export interface NotificationUpdate {
    /** Notification status */
    status?: NotificationUpdate.Status;
    /** Update extended data */
    extendedData?: Record<string, unknown>;
}

export namespace NotificationUpdate {
    /** Notification status */
    export const Status = {
        Read: "read",
        Unread: "unread",
        Dismissed: "dismissed",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
