// This file was auto-generated by Fern from our API Definition.

export interface NotificationList {
    /** Items per page (max 75) */
    limit?: number;
    /** Cursor for pagination */
    cursor?: string;
    /** Filter by notification status */
    status?: NotificationList.Status;
    /** Filter by recipient user ID (admin only) */
    userId?: string;
}

export namespace NotificationList {
    /** Filter by notification status */
    export const Status = {
        Read: "read",
        Unread: "unread",
        Dismissed: "dismissed",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
