// This file was auto-generated by Fern from our API Definition.

export interface PostUpdate {
    /** Updated post content */
    body?: string;
    /** Move post to another thread */
    threadId?: string;
    /** Change parent post */
    parentId?: string;
    /** Update extended data */
    extendedData?: Record<string, unknown>;
}
