// This file was auto-generated by Fern from our API Definition.

export interface ReportList {
    /** Items per page (max 75) */
    limit?: number;
    /** Cursor for pagination */
    cursor?: string;
    /** Filter by status */
    status?: string;
    /** Filter by reporter ID */
    reporterId?: string;
    /** Filter by reported user ID */
    reportedId?: string;
}
