// This file was auto-generated by Fern from our API Definition.

export interface RoleResponse {
    /** Role name */
    name: string;
    /** Role slug (unique identifier) */
    slug?: string;
    /** Role description */
    description?: string;
    /** Role color hex */
    color?: string;
    /** Extended data */
    extendedData?: Record<string, unknown>;
    id: string;
}
