// This file was auto-generated by Fern from our API Definition.

export interface TagCreate {
    /** Tag name */
    name: string;
    /** Tag slug (unique identifier) */
    slug?: string;
    /** Tag description */
    description?: string;
    /** Hex color code */
    color?: string;
    /** Extended data */
    extendedData?: Record<string, unknown>;
}
