// This file was auto-generated by Fern from our API Definition.

export interface TagList {
    /** Items per page (max 75) */
    limit?: number;
    /** Cursor for pagination */
    cursor?: string;
    /** Search tags by name or description */
    search?: string;
}
