// This file was auto-generated by Fern from our API Definition.

export interface ThreadList {
    /** Items per page (max 75) */
    limit?: number;
    /** Cursor for pagination */
    cursor?: string;
    /** Search term for title */
    search?: string;
    /** Filter by tag ID */
    tagId?: string;
    /** Filter by author ID */
    userId?: string;
    /** Sort criteria */
    sort?: ThreadList.Sort;
}

export namespace ThreadList {
    /** Sort criteria */
    export const Sort = {
        Newest: "newest",
        Oldest: "oldest",
        Activity: "activity",
    } as const;
    export type Sort = (typeof Sort)[keyof typeof Sort];
}
