// This file was auto-generated by Fern from our API Definition.

export interface UserList {
    /** Items per page (max 75) */
    limit?: number;
    /** Cursor for pagination */
    cursor?: string;
    /** Search by username or display name */
    search?: string;
    /** Sort by creation date */
    sort?: UserList.Sort;
}

export namespace UserList {
    /** Sort by creation date */
    export const Sort = {
        Newest: "newest",
        Oldest: "oldest",
    } as const;
    export type Sort = (typeof Sort)[keyof typeof Sort];
}
