// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         subId: "subId"
 *     }
 */
export interface GetThreadsIdReactionsSubIdRequest {
    /** Thread ID */
    id: string;
    /** Reaction ID */
    subId: string;
}
