// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetThreadsIdReactionsRequest {
    /** Thread ID */
    id: string;
    /** Pagination cursor */
    cursor?: string;
    /** Items per page */
    limit?: number;
}
