// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface PatchRolesIdRequest {
    id: string;
    /** Role name */
    name?: string;
    /** Role slug (unique identifier) */
    slug?: string;
    /** Role description */
    description?: string;
    /** Role color hex */
    color?: string;
    /** Extended data */
    extendedData?: Record<string, unknown>;
}
