// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface PatchNotificationsIdRequest {
    id: string;
    /** Notification status */
    status?: PatchNotificationsIdRequest.Status;
    /** Update extended data */
    extendedData?: Record<string, unknown>;
}

export namespace PatchNotificationsIdRequest {
    /** Notification status */
    export const Status = {
        Read: "read",
        Unread: "unread",
        Dismissed: "dismissed",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
