// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "userId",
 *         type: "type"
 *     }
 */
export interface PostNotificationsRequest {
    /** Target user ID to receive notification */
    userId: string;
    /** Notification type (e.g. mention, reply, follow) */
    type: string;
    /** Notification title */
    title?: string;
    /** Notification content */
    body?: string;
    /** Link URL for the notification */
    link?: string;
    /** Additional notification data */
    extendedData?: Record<string, unknown>;
}
