// This file was auto-generated by Fern from our API Definition.

export interface GetThreadsIdPostsSubIdResponse {
    data: GetThreadsIdPostsSubIdResponse.Data;
}

export namespace GetThreadsIdPostsSubIdResponse {
    export type Data = {};
}
