// This file was auto-generated by Fern from our API Definition.

export interface GetThreadsIdPollResponse {
    data: GetThreadsIdPollResponse.Data;
}

export namespace GetThreadsIdPollResponse {
    export type Data = {};
}
