// This file was auto-generated by Fern from our API Definition.

export interface GetThreadsIdReactionsSubIdResponse {
    data: GetThreadsIdReactionsSubIdResponse.Data;
}

export namespace GetThreadsIdReactionsSubIdResponse {
    export type Data = {};
}
