// This file was auto-generated by Fern from our API Definition.

export interface GetThreadsIdSubscribersSubIdResponse {
    data: GetThreadsIdSubscribersSubIdResponse.Data;
}

export namespace GetThreadsIdSubscribersSubIdResponse {
    export type Data = {};
}
