// This file was auto-generated by Fern from our API Definition.

export interface GetThreadsResponse {
    data: GetThreadsResponse.Data.Item[];
    meta: GetThreadsResponse.Meta;
}

export namespace GetThreadsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Thread title */
            title: string;
            /** Thread content (Markdown supported) */
            body: string;
            /** Author user ID (required for API key auth, ignored for JWT auth) */
            userId?: string;
            /** List of tag slugs, names, or IDs to attach */
            tags?: string[];
            /** Poll data */
            poll?: Item.Poll;
            id: string;
            createdAt: string;
            updatedAt: string;
        }

        export namespace Item {
            /**
             * Poll data
             */
            export interface Poll {
                /** Poll title */
                title: string;
                /** Poll options */
                options: Poll.Options.Item[];
            }

            export namespace Poll {
                export type Options = Options.Item[];

                export namespace Options {
                    export interface Item {
                        title: string;
                        color?: string;
                        extendedData?: Record<string, unknown>;
                    }
                }
            }
        }
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
