// This file was auto-generated by Fern from our API Definition.

export interface PostThreadsIdReactionsResponse {
    data: PostThreadsIdReactionsResponse.Data;
}

export namespace PostThreadsIdReactionsResponse {
    export type Data = {};
}
