// This file was auto-generated by Fern from our API Definition.

export interface GetPostsResponse {
    data: GetPostsResponse.Data.Item[];
    meta: GetPostsResponse.Meta;
}

export namespace GetPostsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Thread ID to post in */
            threadId: string;
            /** Post content (Markdown supported) */
            body: string;
            /** Author user ID (required for API key auth, ignored for JWT auth) */
            userId?: string;
            /** Parent post ID for threading */
            parentId?: string;
            extendedData?: Record<string, unknown>;
            id: string;
        }
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
