// This file was auto-generated by Fern from our API Definition.

export interface GetPostsIdReactionsSubIdResponse {
    data: GetPostsIdReactionsSubIdResponse.Data;
}

export namespace GetPostsIdReactionsSubIdResponse {
    export type Data = {};
}
