// This file was auto-generated by Fern from our API Definition.

export interface GetPostsIdPostsSubIdResponse {
    data: GetPostsIdPostsSubIdResponse.Data;
}

export namespace GetPostsIdPostsSubIdResponse {
    export type Data = {};
}
