// This file was auto-generated by Fern from our API Definition.

export interface GetPostsIdReactionsResponse {
    data: GetPostsIdReactionsResponse.Data;
}

export namespace GetPostsIdReactionsResponse {
    export interface Data {
        items: Data.Items.Item[];
        nextCursor?: string;
        count: number;
    }

    export namespace Data {
        export type Items = Items.Item[];

        export namespace Items {
            export type Item = {};
        }
    }
}
