// This file was auto-generated by Fern from our API Definition.

export interface PostPostsIdReactionsResponse {
    data: PostPostsIdReactionsResponse.Data;
}

export namespace PostPostsIdReactionsResponse {
    export type Data = {};
}
