// This file was auto-generated by Fern from our API Definition.

import * as Forum from "../../src/api/index";
import { ForumClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PrivateMessagesClient", () => {
    test("listAllPrivateMessages (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: [{}], meta: { total: 1, page: 1, limit: 1 } };
        server.mockEndpoint().get("/private-messages").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.privateMessages.listAllPrivateMessages();
        expect(response).toEqual({
            data: [{}],
            meta: {
                total: 1,
                page: 1,
                limit: 1,
            },
        });
    });

    test("listAllPrivateMessages (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/private-messages").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.privateMessages.listAllPrivateMessages();
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listAllPrivateMessages (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/private-messages").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.privateMessages.listAllPrivateMessages();
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("listAllPrivateMessages (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/private-messages").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.privateMessages.listAllPrivateMessages();
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listAllPrivateMessages (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/private-messages").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.privateMessages.listAllPrivateMessages();
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("createAPrivateMessage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { recipientId: "recipientId", body: "body" };
        const rawResponseBody = { data: {} };
        server
            .mockEndpoint()
            .post("/private-messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.privateMessages.createAPrivateMessage({
            recipientId: "recipientId",
            body: "body",
        });
        expect(response).toEqual({
            data: {},
        });
    });

    test("createAPrivateMessage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { recipientId: "recipientId", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/private-messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.createAPrivateMessage({
                recipientId: "recipientId",
                body: "x",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("createAPrivateMessage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { recipientId: "recipientId", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/private-messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.createAPrivateMessage({
                recipientId: "recipientId",
                body: "x",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("createAPrivateMessage (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { recipientId: "recipientId", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/private-messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.createAPrivateMessage({
                recipientId: "recipientId",
                body: "x",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("createAPrivateMessage (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { recipientId: "recipientId", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/private-messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.createAPrivateMessage({
                recipientId: "recipientId",
                body: "x",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("createAPrivateMessage (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { recipientId: "recipientId", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/private-messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.createAPrivateMessage({
                recipientId: "recipientId",
                body: "x",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("getAPrivateMessage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: {} };
        server
            .mockEndpoint()
            .get("/private-messages/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.privateMessages.getAPrivateMessage({
            id: "id",
        });
        expect(response).toEqual({
            data: {},
        });
    });

    test("getAPrivateMessage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/private-messages/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.getAPrivateMessage({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("getAPrivateMessage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/private-messages/id")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.getAPrivateMessage({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("getAPrivateMessage (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/private-messages/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.getAPrivateMessage({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("getAPrivateMessage (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/private-messages/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.getAPrivateMessage({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("getAPrivateMessage (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/private-messages/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.getAPrivateMessage({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteAPrivateMessage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };
        server
            .mockEndpoint()
            .delete("/private-messages/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.privateMessages.deleteAPrivateMessage({
            id: "id",
        });
        expect(response).toEqual({
            success: true,
        });
    });

    test("deleteAPrivateMessage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/private-messages/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.deleteAPrivateMessage({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteAPrivateMessage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/private-messages/id")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.deleteAPrivateMessage({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("deleteAPrivateMessage (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/private-messages/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.deleteAPrivateMessage({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteAPrivateMessage (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/private-messages/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.deleteAPrivateMessage({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteAPrivateMessage (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/private-messages/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privateMessages.deleteAPrivateMessage({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });
});
