// This file was auto-generated by Fern from our API Definition.

import * as Forum from "../../src/api/index";
import { ForumClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ThreadsClient", () => {
    test("listAllThreads (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    title: "title",
                    body: "body",
                    userId: "userId",
                    tags: ["tags"],
                    poll: { title: "title", options: [{ title: "title" }] },
                    id: "id",
                    createdAt: "createdAt",
                    updatedAt: "updatedAt",
                },
            ],
            meta: { total: 1, page: 1, limit: 1 },
        };
        server.mockEndpoint().get("/threads").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.threads.listAllThreads();
        expect(response).toEqual({
            data: [
                {
                    title: "title",
                    body: "body",
                    userId: "userId",
                    tags: ["tags"],
                    poll: {
                        title: "title",
                        options: [
                            {
                                title: "title",
                            },
                        ],
                    },
                    id: "id",
                    createdAt: "createdAt",
                    updatedAt: "updatedAt",
                },
            ],
            meta: {
                total: 1,
                page: 1,
                limit: 1,
            },
        });
    });

    test("listAllThreads (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.listAllThreads();
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listAllThreads (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.listAllThreads();
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("listAllThreads (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.listAllThreads();
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listAllThreads (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.listAllThreads();
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("createAThread (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", body: "body" };
        const rawResponseBody = {
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: { title: "title", options: [{ title: "title" }] },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.createAThread({
            title: "title",
            body: "body",
        });
        expect(response).toEqual({
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: {
                    title: "title",
                    options: [
                        {
                            title: "title",
                        },
                    ],
                },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("createAThread (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createAThread({
                title: "x",
                body: "x",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("createAThread (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createAThread({
                title: "x",
                body: "x",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("createAThread (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createAThread({
                title: "x",
                body: "x",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("createAThread (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createAThread({
                title: "x",
                body: "x",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("createAThread (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createAThread({
                title: "x",
                body: "x",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("getAThread (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: { title: "title", options: [{ title: "title" }] },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.threads.getAThread({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: {
                    title: "title",
                    options: [
                        {
                            title: "title",
                        },
                    ],
                },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("getAThread (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.getAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("getAThread (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.getAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("getAThread (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.getAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("getAThread (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.getAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("getAThread (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.getAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteAThread (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.threads.deleteAThread({
            id: "id",
        });
        expect(response).toEqual({
            success: true,
        });
    });

    test("deleteAThread (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.deleteAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteAThread (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.deleteAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("deleteAThread (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.deleteAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteAThread (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.deleteAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteAThread (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.deleteAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("updateAThread (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: { title: "title", options: [{ title: "title" }] },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.updateAThread({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: {
                    title: "title",
                    options: [
                        {
                            title: "title",
                        },
                    ],
                },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("updateAThread (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updateAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("updateAThread (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updateAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("updateAThread (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updateAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("updateAThread (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updateAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("updateAThread (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updateAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("updateAThread (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updateAThread({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });
});
