// This file was auto-generated by Fern from our API Definition.

export interface GetIntegrationsResponse {
    data: GetIntegrationsResponse.Data.Item[];
    meta: GetIntegrationsResponse.Meta;
}

export namespace GetIntegrationsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export type Item = {};
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
