// This file was auto-generated by Fern from our API Definition.

export interface GetIntegrationsIdResponse {
    data: GetIntegrationsIdResponse.Data;
}

export namespace GetIntegrationsIdResponse {
    export type Data = {};
}
