// This file was auto-generated by Fern from our API Definition.

export interface PatchIntegrationsIdResponse {
    data: PatchIntegrationsIdResponse.Data;
}

export namespace PatchIntegrationsIdResponse {
    export type Data = {};
}
