// This file was auto-generated by Fern from our API Definition.

export interface PostIntegrationsResponse {
    data: PostIntegrationsResponse.Data;
}

export namespace PostIntegrationsResponse {
    export type Data = {};
}
