// This file was auto-generated by Fern from our API Definition.

export interface GetNotificationsIdResponse {
    data: GetNotificationsIdResponse.Data;
}

export namespace GetNotificationsIdResponse {
    export type Data = {};
}
