// This file was auto-generated by Fern from our API Definition.

export interface GetNotificationsResponse {
    data: GetNotificationsResponse.Data.Item[];
    meta: GetNotificationsResponse.Meta;
}

export namespace GetNotificationsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export type Item = {};
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
