// This file was auto-generated by Fern from our API Definition.

export interface PatchNotificationsIdResponse {
    data: PatchNotificationsIdResponse.Data;
}

export namespace PatchNotificationsIdResponse {
    export type Data = {};
}
