// This file was auto-generated by Fern from our API Definition.

export interface PostNotificationsResponse {
    data: PostNotificationsResponse.Data;
}

export namespace PostNotificationsResponse {
    export type Data = {};
}
