// This file was auto-generated by Fern from our API Definition.

export interface GetRolesResponse {
    data: GetRolesResponse.Data.Item[];
    meta: GetRolesResponse.Meta;
}

export namespace GetRolesResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Role name */
            name: string;
            /** Role slug (unique identifier) */
            slug?: string;
            /** Role description */
            description?: string;
            /** Role color hex */
            color?: string;
            /** Extended data */
            extendedData?: Record<string, unknown>;
            id: string;
            /** Role creation timestamp */
            createdAt: string;
            /** Role last update timestamp */
            updatedAt: string;
        }
    }

    export interface Meta {
        total: number;
        page: number;
        limit: number;
    }
}
